name: Python File Test
on:
  push:
    branches:
      - main
jobs:
  Action:
    name: Python Setup
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
    - name: Set-up Virtual Enviroment
      run: |
        pip install virtualenv | python -m virtualenv venv
        ./venv/Scripts/activate
    - name: Install Dependancies
      run: python -m pip install -r requirements.txt
    - name: Run Python File
      run: python File_Manager.py
